[0m21:04:46.744759 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104a5ece0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106552ad0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106552f20>]}


============================== 21:04:46.748620 | 4467814d-c820-4cde-97ac-f5fd1bbd17f5 ==============================
[0m21:04:46.748620 [info ] [MainThread]: Running with dbt=1.6.6
[0m21:04:46.749129 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/Users/nicholas.goldberg/.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt init', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m21:05:07.807920 [debug] [MainThread]: Starter project path: /Users/nicholas.goldberg/.pyenv/versions/3.10.5/lib/python3.10/site-packages/dbt/include/starter_project
[0m21:05:07.823447 [info ] [MainThread]: 
Your new dbt project "chess_dbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m21:05:07.824200 [info ] [MainThread]: Setting up your profile.
[0m21:05:12.695577 [debug] [MainThread]: Command `dbt init` succeeded at 21:05:12.695444 after 26.03 seconds
[0m21:05:12.696028 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104a5ece0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105bae3b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105baee60>]}
[0m21:05:12.696315 [debug] [MainThread]: Flushing usage events
[0m21:08:15.821843 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1052a6ce0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106d9ab90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106d9afe0>]}


============================== 21:08:15.825523 | b4bf91f5-5526-4632-a5a6-8bc307e9071c ==============================
[0m21:08:15.825523 [info ] [MainThread]: Running with dbt=1.6.6
[0m21:08:15.825951 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/Users/nicholas.goldberg/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m21:08:15.826429 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/nicholas.goldberg/chess-analytics/DBT/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m21:08:15.826865 [debug] [MainThread]: Command `dbt run` failed at 21:08:15.826792 after 0.03 seconds
[0m21:08:15.827129 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1052a6ce0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106406770>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106d9b160>]}
[0m21:08:15.827352 [debug] [MainThread]: Flushing usage events
